spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: vodtbank
  profiles:
    active: mysql
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: ${SERVER_PORT:8080}

