spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: vodtbank
  profiles:
    active: mysql
  ### JPA Configuration ###
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  ### Mail Configuration ###
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

### Jwt Configuration ###
jwt:
  public-path: ${JWT_PUBLIC_KEY_LOCATION:classpath:jwt/public.pem}
  private-path: ${JWT_PRIVATE_KEY_LOCATION:classpath:jwt/private.pem}
  expiration: ${JWT_EXPIRATION:3600000} # milliseconds

### Logging Configuration ###
logging:
  level:
    org.springframework.security: TRACE
    com.vodtbank: TRACE

### Password Configuration ###
password:
  base-url: ${PASSWORD_RESET_LINK:http://localhost:8090/api/reset-password?code=}

### Admin Configuration ###
admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}